### ISSUE TITLE
The number of particles is computed wrong in ElementalDust import from buffer

### ISSUE THREAD

**Issue by ReDEnergy** [ZaharescuMihai/TDMRC-2015#1]
ElementalDust.cpp LINE 131: 
nr_particles_int = size/2;

it is suppose to be size/4;

Also I'm pretty sure buffer comparison doesn't work. 
I'm just having fun testing the code instead of solving the assignment...

**Comment by ZaharescuMihai** [comment]
Thank you; merged with your fix.
