### ISSUE TITLE
fixed_float contructor / getFloat() error

### ISSUE THREAD

**Issue by emanuelUngureanu** [ZaharescuMihai/TDMRC-2015#10]
I think there might be a problem with the way fixed_float is constructed
of with the result returned by getFloat().

test 1:
fixed_float test(1.234 )
float res =  test.getFloat()
res = 1.23046875
//expected result : 1.234

test 2:
fixed_float test(1,234 )
float res =  test.getFloat()
res = 1.91406250
//expected result : 1.234

Update:
Wrote wrong res values.

**Comment by ZaharescuMihai** [comment]
It may just be a precision issue: it tries to store 3 decimals in 8 bits, so it looses the less significant parts. I will investigate and close the issue if it is just a precision problem.

**Comment by emanuelUngureanu** [comment]
From what i understand, fixed_float represents numbers ranging from  0.0 to 255.255 . Or maybe I don't use it properly.

**Comment by emanuelUngureanu** [comment]
Ok, It works properly. I didn't use it properly :). The fractional part of float values is a mapping between [0,1) to [0, 256).
Issue can be closed. Sorry for the wrong alert, i'll try to understand the code better next time.
